# waylock.toml

[colors]
# Specify the initial color of the lock screen.
init_color = 0xF2E9E4
# Specify the color of the lock screen after input is received.
input_color = 0x4A4E69
# Specify the color of the lock screen on authentication failure.
fail_color = 0xC9ADA7
