print_info() {
    info underline
    info underline
    info distro
    prin "Linux "
    info uptime
    info packages
    info shell
    info resolution
    info wm
    info term
    info cpu
    prin "GTX 750Ti"
    info memory
    info cols
}

title_fqdn="off"
kernel_shorthand="off"
# Values:   'on', 'tiny', 'off'
# Flag:     --distro_shorthand
# Supports: Everything except Windows and Haiku
distro_shorthand="tiny"
os_arch="off"
uptime_shorthand="tiny"
memory_percent="off"
package_managers="off"
shell_path="off"
shell_version="off"
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="off"
cpu_speed="off"
cpu_cores="off"
cpu_temp="off"
gpu_brand="off"
gpu_type="all"
refresh_rate="off"
gtk_shorthand="on"
gtk2="off"
gtk3="on"
public_ip_host="http://ident.me"
public_ip_timeout=2
de_version="off"
disk_show=('/')
disk_subtitle="none"
disk_percent="on"
music_player="auto"
song_format="%artist% - %album% - %title%"
song_shorthand="off"
mpc_args=()
# this order: 'title', '@', 'underline', 'subtitle', 'colon', 'info'
# colors=(distro)      - Text is colored based on Distro colors.
# colors=(4 6 1 8 8 6) - Text is colored in the order above.
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="-"
separator="->"
block_range=(0 15)
color_blocks="on"
block_width=2.5
block_height=1
col_offset="auto"
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"


# Info display
# Display a bar with the info.
#
# Default: 'off'
# Values:  'bar', 'infobar', 'barinfo', 'off'
# Flags:   --cpu_display
#          --memory_display
#          --battery_display
#          --disk_display
#
# Example:
# bar:     '[---=======]'
# infobar: 'info [---=======]'
# barinfo: '[---=======] info'
# off:     'info'
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="caca"
image_source="wallpaper"
ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="400px"
gap=2
yoffset=0
xoffset=0
background_color= 
stdout="off"
